// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/l1ancg/data-viewer/backend/config"
	"github.com/l1ancg/data-viewer/backend/internal/application"
	"github.com/l1ancg/data-viewer/backend/internal/repository"
	"github.com/l1ancg/data-viewer/backend/internal/server"
)

// Injectors from gen.go:

func NewServer() *server.Server {
	configConfig := config.NewConfig()
	db := repository.DBProvider(configConfig)
	service := application.ServiceProvider(db)
	graphQLHandler := server.GraphQLHandlerProvider(service)
	serverServer := server.HttpServerProvider(configConfig, graphQLHandler)
	return serverServer
}
