// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/l1ancg/data-viewer/backend/internal/server"
	"github.com/l1ancg/data-viewer/backend/internal/service"
	"github.com/l1ancg/data-viewer/backend/pkg/config"
	"github.com/l1ancg/data-viewer/backend/pkg/db"
)

// Injectors from gen.go:

func NewServer() *server.Server {
	configConfig := config.NewConfig()
	dbDB := db.DBprovider(configConfig)
	serviceService := service.ServiceProvider(dbDB)
	serverServer := server.ServerProvider(configConfig, serviceService)
	return serverServer
}
