name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            type: linux
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@master
      with:
        ref: ${{ github.event.inputs.tag }}

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build
      run: make build-all

    - name: Upload release binaries
      uses: AButler/upload-release-assets@v3.0
      with:
        repo-token: ${{ secrets.GH_TOKEN }}
        release-tag: ${{ github.event.inputs.tag }}
        files: "./bin/data-viewer*"